export type Level = 'Primary' | 'Junior' | 'Senior' | 'Olympiad' | 'All Levels'
export type Region =
  | 'Thailand'
  | 'School Open'
  | 'Asia-Pacific'
  | 'Southeast Asia'
  | 'International'
  | 'USA'
  | 'Europe'
  | 'Australia'
  | 'Online'

export interface Competition {
  id: string
  name: string
  fullName: string
  nameThai?: string
  description: string
  levels: Level[]          // who can participate
  region: Region
  topics: string[]
  url: string
  solutionsUrl?: string
  difficulty: 1 | 2 | 3 | 4 | 5
  hasPastPapers: boolean   // true = direct past paper link; false = registration needed
  note?: string            // short caveat e.g. "registration required"
}

export const DIFFICULTY_LABEL: Record<number, string> = {
  1: 'Intro',
  2: 'Intermediate',
  3: 'Advanced',
  4: 'Olympiad',
  5: 'Elite',
}

export const ALL_COMPETITIONS: Competition[] = [
  // ─── THAILAND ───────────────────────────────────────────────────────────────
  {
    id: 'soawn',
    name: 'สอวน.',
    fullName: 'สอวน. คณิตศาสตร์ (POSN)',
    nameThai: 'การแข่งขันคัดเลือกเข้าค่ายโอลิมปิกวิชาการ',
    description: 'ข้อสอบคัดเลือกเข้าค่าย 1 และค่าย 2 — เส้นทางสู่ IMO ของนักเรียนไทย',
    levels: ['Junior', 'Senior'],
    region: 'Thailand',
    topics: ['Number Theory', 'Algebra', 'Geometry', 'Combinatorics'],
    url: 'https://www.posn.or.th/projects/academic-olympiad/mo/examination/',
    solutionsUrl: 'https://artofproblemsolving.com/community/c558627',
    difficulty: 4,
    hasPastPapers: true,
  },
  {
    id: 'timo',
    name: 'TIMO',
    fullName: 'Thailand International Mathematical Olympiad',
    nameThai: 'การแข่งขันคณิตศาสตร์นานาชาติประเทศไทย',
    description: 'การแข่งขันระดับนานาชาติที่จัดในไทย มีรอบ Heat และ Final แยกตามระดับชั้น ป.3–ม.6',
    levels: ['Primary', 'Junior', 'Senior'],
    region: 'Thailand',
    topics: ['Logic', 'Algebra', 'Number Theory', 'Geometry', 'Combinatorics'],
    url: 'https://www.thaiimo.com/sample-paper.html',
    difficulty: 2,
    hasPastPapers: true,
    note: 'Sample papers free; full past papers via registration',
  },
  {
    id: 'pat1',
    name: 'PAT 1',
    fullName: 'ความถนัดทางคณิตศาสตร์ (PAT 1)',
    description: 'ข้อสอบ TCAS ความถนัดคณิตศาสตร์ — จัดโดย สทศ. ใช้คัดเลือกเข้ามหาวิทยาลัย',
    levels: ['Senior'],
    region: 'Thailand',
    topics: ['Algebra', 'Calculus', 'Statistics', 'Geometry'],
    url: 'https://www.niets.or.th/th/catalog/view/28',
    difficulty: 2,
    hasPastPapers: true,
  },
  {
    id: 'kvis',
    name: 'KVIS / PSIT',
    fullName: 'โรงเรียนวิทยาศาสตร์จุฬาภรณราชวิทยาลัย',
    description: 'ข้อสอบคัดเลือกเข้าโรงเรียนวิทยาศาสตร์ กพว. — เน้น Pattern Recognition และ Problem Solving ระดับ ม.ต้น',
    levels: ['Junior'],
    region: 'Thailand',
    topics: ['Logic', 'Algebra', 'Number Theory', 'Geometry'],
    url: 'https://www.kvis.ac.th',
    difficulty: 2,
    hasPastPapers: false,
    note: 'Past papers available through prep books',
  },
  {
    id: 'pcsn',
    name: 'พสวท.',
    fullName: 'โครงการพัฒนาและส่งเสริมผู้มีความสามารถพิเศษ (พสวท.)',
    description: 'ข้อสอบคัดเลือกนักเรียนทุน พสวท. ม.ต้น และ ม.ปลาย — เน้น Problem Solving คณิต-วิทย์',
    levels: ['Junior', 'Senior'],
    region: 'Thailand',
    topics: ['Algebra', 'Geometry', 'Number Theory'],
    url: 'https://www.posn.or.th/en/examination/',
    difficulty: 3,
    hasPastPapers: true,
  },

  // ─── SCHOOL OPEN (Thailand) ──────────────────────────────────────────────────
  {
    id: 'mwit-open',
    name: 'MWIT Open',
    fullName: 'การแข่งขันคณิตศาสตร์เปิด มหิดลวิทยานุสรณ์',
    nameThai: 'โรงเรียนมหิดลวิทยานุสรณ์',
    description: 'การแข่งขันคณิตศาสตร์เปิด จัดโดยโรงเรียนมหิดลวิทยานุสรณ์ — ระดับยากใกล้เคียง สอวน. ค่าย 1 รับนักเรียน ม.ต้น–ม.ปลายจากทั่วประเทศ',
    levels: ['Junior', 'Senior'],
    region: 'School Open',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://www.mwit.ac.th',
    difficulty: 3,
    hasPastPapers: false,
    note: 'ติดตามกำหนดการทาง Facebook โรงเรียน / จัดประมาณ พ.ย.–ธ.ค.',
  },
  {
    id: 'benchama-open',
    name: 'เบญจมมหาราช Open',
    fullName: 'การแข่งขันคณิตศาสตร์เปิดโรงเรียนเบญจมมหาราช',
    nameThai: 'โรงเรียนเบญจมมหาราช จ.อุบลราชธานี',
    description: 'การแข่งขันคณิตศาสตร์เปิด จัดโดยโรงเรียนเบญจมมหาราช อุบลราชธานี — รับนักเรียนจากทุกโรงเรียนระดับ ม.ต้น–ม.ปลาย',
    levels: ['Junior', 'Senior'],
    region: 'School Open',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://www.benchama.ac.th',
    difficulty: 2,
    hasPastPapers: false,
    note: 'ติดตามกำหนดการทาง Facebook โรงเรียน / จัดประมาณ พ.ย.–ม.ค.',
  },
  {
    id: 'roietwit-open',
    name: 'ร้อยเอ็ดวิทยาลัย Open',
    fullName: 'การแข่งขันคณิตศาสตร์เปิดโรงเรียนร้อยเอ็ดวิทยาลัย',
    nameThai: 'โรงเรียนร้อยเอ็ดวิทยาลัย จ.ร้อยเอ็ด',
    description: 'การแข่งขันคณิตศาสตร์เปิด จัดโดยโรงเรียนร้อยเอ็ดวิทยาลัย — รับนักเรียนจากภาคอีสานและทั่วประเทศ ม.ต้น–ม.ปลาย',
    levels: ['Junior', 'Senior'],
    region: 'School Open',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://www.roietwit.ac.th',
    difficulty: 2,
    hasPastPapers: false,
    note: 'ติดตามกำหนดการทาง Facebook โรงเรียน',
  },
  {
    id: 'sk-open',
    name: 'สวนกุหลาบ Open',
    fullName: 'การแข่งขันคณิตศาสตร์เปิดโรงเรียนสวนกุหลาบวิทยาลัย',
    nameThai: 'โรงเรียนสวนกุหลาบวิทยาลัย กรุงเทพฯ',
    description: 'การแข่งขันคณิตศาสตร์เปิด จัดโดยโรงเรียนสวนกุหลาบวิทยาลัย กรุงเทพฯ — รับนักเรียนจากทั่วประเทศ ม.ต้น–ม.ปลาย',
    levels: ['Junior', 'Senior'],
    region: 'School Open',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://www.sk.ac.th',
    difficulty: 2,
    hasPastPapers: false,
    note: 'ติดตามกำหนดการทาง Facebook โรงเรียน',
  },
  {
    id: 'satitchula-open',
    name: 'สาธิตจุฬาฯ Open',
    fullName: 'การแข่งขันคณิตศาสตร์เปิดโรงเรียนสาธิตจุฬาลงกรณ์มหาวิทยาลัย',
    nameThai: 'โรงเรียนสาธิตจุฬาลงกรณ์มหาวิทยาลัย กรุงเทพฯ',
    description: 'การแข่งขันคณิตศาสตร์เปิด จัดโดยโรงเรียนสาธิตจุฬาฯ — รับนักเรียน ม.ต้น–ม.ปลาย จากทั่วประเทศ',
    levels: ['Junior', 'Senior'],
    region: 'School Open',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://www.satitchula.ac.th',
    difficulty: 2,
    hasPastPapers: false,
    note: 'ติดตามกำหนดการทาง Facebook โรงเรียน',
  },
  {
    id: 'triam-open',
    name: 'เตรียมอุดม Open',
    fullName: 'การแข่งขันคณิตศาสตร์เปิดโรงเรียนเตรียมอุดมศึกษา',
    nameThai: 'โรงเรียนเตรียมอุดมศึกษา กรุงเทพฯ',
    description: 'การแข่งขันคณิตศาสตร์เปิด จัดโดยโรงเรียนเตรียมอุดมศึกษา — ระดับ ม.ปลาย รับสมัครจากทั่วประเทศ',
    levels: ['Senior'],
    region: 'School Open',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://www.triamudom.ac.th',
    difficulty: 3,
    hasPastPapers: false,
    note: 'ติดตามกำหนดการทาง Facebook โรงเรียน',
  },

  // ─── SOUTHEAST ASIA ─────────────────────────────────────────────────────────
  {
    id: 'iwymic',
    name: 'IWYMIC / IMC',
    fullName: 'Invitational World Youth Mathematics Intercity Competition',
    nameThai: 'การแข่งขันคณิตศาสตร์นานาชาติระดับเมือง',
    description: 'เดิมชื่อ IWYMIC ปัจจุบันรวมกับ IMC — ทีมเมือง 4 คน, Individual + Team Round, จัดโดย Chiuchang (ไต้หวัน)',
    levels: ['Junior'],
    region: 'Asia-Pacific',
    topics: ['Number Theory', 'Algebra', 'Geometry', 'Combinatorics'],
    url: 'https://chiuchang.org/imc/en/%E6%AD%B7%E5%B1%86%E8%A9%A6%E9%A1%8C/',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/International_Mathematics_Competition',
    difficulty: 3,
    hasPastPapers: true,
  },
  {
    id: 'imas',
    name: 'IMAS',
    fullName: 'International Mathematics Assessments for Schools',
    nameThai: 'การประเมินคณิตศาสตร์นานาชาติสำหรับนักเรียน',
    description: '2 รอบ — First Round (ปรนัย) และ Second Round (อัตนัย); มี Junior (ม.1–ม.2) และ Upper Primary. จัดโดย Chiuchang',
    levels: ['Primary', 'Junior'],
    region: 'Asia-Pacific',
    topics: ['Algebra', 'Number Theory', 'Geometry', 'Combinatorics'],
    url: 'https://chiuchang.org/imas/en/%E6%AD%B7%E5%B1%86%E8%A9%A6%E9%A1%8C/',
    difficulty: 2,
    hasPastPapers: true,
  },
  {
    id: 'hkimo',
    name: 'HKIMO',
    fullName: 'Hong Kong International Mathematical Olympiad',
    nameThai: 'การแข่งขันคณิตศาสตร์นานาชาติฮ่องกง',
    description: '5 หัวข้อ: Logical Thinking, Algebra, Number Theory, Geometry, Combinatorics — มีทุกระดับ KG–ม.6, Heat + Final Round',
    levels: ['Primary', 'Junior', 'Senior'],
    region: 'Asia-Pacific',
    topics: ['Logic', 'Algebra', 'Number Theory', 'Geometry', 'Combinatorics'],
    url: 'https://www.hongkongimo.com/',
    solutionsUrl: 'https://smo-testing.com/hkimo/',
    difficulty: 3,
    hasPastPapers: false,
    note: 'Past papers via registration / prep centers',
  },
  {
    id: 'sasmo',
    name: 'SASMO',
    fullName: 'Singapore and Asian Schools Math Olympiad',
    nameThai: 'การแข่งขันคณิตศาสตร์สิงคโปร์และเอเชีย',
    description: 'กว่า 120,000 ผู้เข้าแข่งขันใน 20+ ประเทศ — 25 ข้อ (MCQ + Short Answer) สำหรับทุกระดับ ป.1–ม.6',
    levels: ['Primary', 'Junior', 'Senior'],
    region: 'Southeast Asia',
    topics: ['Algebra', 'Number Theory', 'Geometry', 'Logic', 'Combinatorics'],
    url: 'https://sasmo.sg/',
    solutionsUrl: 'https://smo-testing.com/sasmo/',
    difficulty: 2,
    hasPastPapers: false,
    note: 'Sample papers free at sasmo.sg',
  },
  {
    id: 'seamo',
    name: 'SEAMO',
    fullName: 'Southeast Asian Mathematical Olympiad',
    nameThai: 'การแข่งขันคณิตศาสตร์เอเชียตะวันออกเฉียงใต้',
    description: '18+ ประเทศ, จัดแยกระดับ A–F (ป.3–ม.4) — เน้น Higher Order Thinking',
    levels: ['Primary', 'Junior', 'Senior'],
    region: 'Southeast Asia',
    topics: ['Algebra', 'Number Theory', 'Geometry', 'Combinatorics'],
    url: 'https://seamo-official.org/',
    difficulty: 2,
    hasPastPapers: false,
    note: 'Past papers available via SEAMO Portal (login)',
  },
  {
    id: 'ijmo',
    name: 'IJMO',
    fullName: 'International Junior Math Olympiad',
    nameThai: 'การแข่งขันคณิตศาสตร์โอลิมปิกระดับมัธยมต้นนานาชาติ',
    description: 'จัดโดย SIMCC — 30 ข้อ 90 นาที, 50+ ประเทศ, สำหรับ ป.1–ม.6 โดยมุ่งเน้น ม.ต้น',
    levels: ['Primary', 'Junior'],
    region: 'Southeast Asia',
    topics: ['Algebra', 'Number Theory', 'Geometry', 'Combinatorics'],
    url: 'https://ijmo.asia/',
    solutionsUrl: 'https://simcc.org/global-tier-1-contest-ijmo-international-junior-math-olympiad/',
    difficulty: 3,
    hasPastPapers: false,
    note: 'Past papers via SIMCC portal',
  },
  {
    id: 'simoc',
    name: 'SIMOC',
    fullName: 'Singapore International Math Olympiad Challenge',
    nameThai: 'การแข่งขันคณิตศาสตร์นานาชาติสิงคโปร์ชาเลนจ์',
    description: 'Individual + Team relay rounds — จัดที่สิงคโปร์, มี Mental Arithmetic ด้วย, ระดับ ป.3–ม.5',
    levels: ['Primary', 'Junior', 'Senior'],
    region: 'Southeast Asia',
    topics: ['Algebra', 'Number Theory', 'Geometry', 'Combinatorics', 'Mental Math'],
    url: 'https://simoc.sg/sample-papers/',
    difficulty: 2,
    hasPastPapers: true,
    note: 'Sample papers available at simoc.sg',
  },
  {
    id: 'pmwc',
    name: 'PMWC',
    fullName: 'Po Leung Kuk Primary Mathematics World Contest',
    nameThai: 'การแข่งขันคณิตศาสตร์โลกระดับประถมและมัธยมต้น',
    description: 'จัดที่ฮ่องกง — Individual (15 ข้อ) + Team Round, สำหรับนักเรียนอายุไม่เกิน 13 ปี',
    levels: ['Primary', 'Junior'],
    region: 'Asia-Pacific',
    topics: ['Algebra', 'Number Theory', 'Geometry', 'Combinatorics'],
    url: 'https://www.txst.edu/mathworks/pmwc/previous-pmwc-tests.html',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/Primary_Mathematics_World_Contest',
    difficulty: 3,
    hasPastPapers: true,
  },
  {
    id: 'wmtc',
    name: 'WMTC',
    fullName: 'World Mathematics Team Championship',
    nameThai: 'การแข่งขันคณิตศาสตร์ทีมโลก',
    description: 'แข่งเป็นทีม — Individual + Relay + Team Round; มีระดับ Junior, Intermediate, Senior',
    levels: ['Primary', 'Junior', 'Senior'],
    region: 'International',
    topics: ['Algebra', 'Number Theory', 'Geometry', 'Combinatorics'],
    url: 'https://wmtc.international/competition',
    difficulty: 3,
    hasPastPapers: false,
    note: 'Past papers available through prep centers',
  },
  {
    id: 'smo-junior',
    name: 'SMO Junior',
    fullName: 'Singapore Mathematical Olympiad — Junior Section',
    nameThai: 'การแข่งขันคณิตศาสตร์โอลิมปิกสิงคโปร์ ระดับมัธยมต้น',
    description: 'จัดโดย Singapore Mathematical Society — Round 1 (35 MCQ) + Round 2 (พิสูจน์) คล้าย AMC 10 ในความยาก',
    levels: ['Junior'],
    region: 'Southeast Asia',
    topics: ['Algebra', 'Number Theory', 'Geometry', 'Combinatorics'],
    url: 'https://sms.math.nus.edu.sg/download/sample_smo_questions.pdf',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/Singapore_mathematics_competitions',
    difficulty: 3,
    hasPastPapers: true,
  },
  {
    id: 'itym',
    name: 'ITYM',
    fullName: 'International Tournament of Young Mathematicians',
    nameThai: 'การแข่งขันคณิตศาสตร์แบบทีม นานาชาติ',
    description: 'ไม่ใช่ข้อสอบ แต่เป็น Tournament-style: ทีมนำเสนอการพิสูจน์ต่อหน้า Jury — สำหรับ ม.ปลาย / ป.1 มหาวิทยาลัย',
    levels: ['Senior', 'Olympiad'],
    region: 'International',
    topics: ['Algebra', 'Analysis', 'Number Theory', 'Combinatorics', 'Geometry'],
    url: 'https://www.itym.org/',
    solutionsUrl: 'https://pyims.com/wp-content/uploads/2023/09/Problems-ITYM2023-1.pdf',
    difficulty: 5,
    hasPastPapers: true,
    note: 'Problems released months in advance — some open-ended',
  },

  // ─── INTERNATIONAL OLYMPIAD ──────────────────────────────────────────────────
  {
    id: 'imo',
    name: 'IMO',
    fullName: 'International Mathematical Olympiad',
    nameThai: 'การแข่งขันคณิตศาสตร์โอลิมปิกระดับโลก',
    description: '6 ข้อ ใน 2 วัน — ยากที่สุดในโลก ใช้คัดทีมชาติแต่ละประเทศ',
    levels: ['Senior', 'Olympiad'],
    region: 'International',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://www.imo-official.org/problems.aspx',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/IMO_Problems_and_Solutions',
    difficulty: 5,
    hasPastPapers: true,
  },
  {
    id: 'apmo',
    name: 'APMO',
    fullName: 'Asian Pacific Mathematics Olympiad',
    nameThai: 'การแข่งขันคณิตศาสตร์โอลิมปิกเอเชีย-แปซิฟิก',
    description: 'ขั้นกลางระหว่าง สอวน. ค่าย 2 และ IMO — 5 ข้อ 4 ชั่วโมง',
    levels: ['Senior', 'Olympiad'],
    region: 'Asia-Pacific',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://www.apmo-official.org/problems_and_solutions',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/APMO_Problems_and_Solutions',
    difficulty: 4,
    hasPastPapers: true,
  },
  {
    id: 'jbmo',
    name: 'JBMO',
    fullName: 'Junior Balkan Mathematical Olympiad',
    nameThai: 'การแข่งขันคณิตศาสตร์โอลิมปิกบอลข่านระดับจูเนียร์',
    description: '4 ข้อ เขียนพิสูจน์ — เหมาะสำหรับ ม.ต้น–ม.ปลายตอนต้น ที่ฝึก Proof Writing',
    levels: ['Junior', 'Senior'],
    region: 'Europe',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://artofproblemsolving.com/wiki/index.php/Junior_Balkan_Mathematical_Olympiad',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/Junior_Balkan_Mathematical_Olympiad',
    difficulty: 3,
    hasPastPapers: true,
  },
  {
    id: 'egmo',
    name: 'EGMO',
    fullName: "European Girls' Mathematical Olympiad",
    description: '6 ข้อ 2 วัน — ระดับใกล้เคียง IMO สำหรับนักเรียนหญิง',
    levels: ['Senior', 'Olympiad'],
    region: 'Europe',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://www.egmo.org/egmos/',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/EGMO_Problems_and_Solutions',
    difficulty: 4,
    hasPastPapers: true,
  },
  {
    id: 'usamo',
    name: 'USAMO',
    fullName: 'USA Mathematical Olympiad',
    description: '6 ข้อ Proof-based — คัดทีม USA ไป IMO',
    levels: ['Senior', 'Olympiad'],
    region: 'USA',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://artofproblemsolving.com/wiki/index.php/USAMO_Problems_and_Solutions',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/USAMO_Problems_and_Solutions',
    difficulty: 5,
    hasPastPapers: true,
  },
  {
    id: 'imo-shortlist',
    name: 'IMO Shortlist',
    fullName: 'IMO Shortlisted Problems',
    description: 'ข้อสอบที่ผ่านรอบคัดแต่ไม่ได้ใช้จริง — มีทุกระดับ C1–C7, A1–A7, N1–N7, G1–G8',
    levels: ['Senior', 'Olympiad'],
    region: 'International',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://artofproblemsolving.com/wiki/index.php/IMO_Shortlist',
    difficulty: 5,
    hasPastPapers: true,
  },

  // ─── USA ─────────────────────────────────────────────────────────────────────
  {
    id: 'amc8',
    name: 'AMC 8',
    fullName: 'American Mathematics Competition 8',
    description: '25 ข้อ ปรนัย 40 นาที — สำหรับ ม.ต้น (Grade ≤ 8) เน้น Problem Solving พื้นฐาน',
    levels: ['Primary', 'Junior'],
    region: 'USA',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Logic'],
    url: 'https://artofproblemsolving.com/wiki/index.php/AMC_8_Problems_and_Solutions',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/AMC_8_Problems_and_Solutions',
    difficulty: 1,
    hasPastPapers: true,
  },
  {
    id: 'amc10',
    name: 'AMC 10',
    fullName: 'American Mathematics Competition 10',
    description: '30 ข้อ ปรนัย 75 นาที — สำหรับ Grade ≤ 10, เส้นทางสู่ AIME',
    levels: ['Junior', 'Senior'],
    region: 'USA',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://artofproblemsolving.com/wiki/index.php/AMC_10_Problems_and_Solutions',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/AMC_10_Problems_and_Solutions',
    difficulty: 2,
    hasPastPapers: true,
  },
  {
    id: 'amc12',
    name: 'AMC 12',
    fullName: 'American Mathematics Competition 12',
    description: '30 ข้อ ปรนัย 75 นาที — ครอบคลุม Pre-Calculus, Grade ≤ 12',
    levels: ['Senior'],
    region: 'USA',
    topics: ['Algebra', 'Geometry', 'Trigonometry', 'Number Theory', 'Combinatorics'],
    url: 'https://artofproblemsolving.com/wiki/index.php/AMC_12_Problems_and_Solutions',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/AMC_12_Problems_and_Solutions',
    difficulty: 3,
    hasPastPapers: true,
  },
  {
    id: 'aime',
    name: 'AIME',
    fullName: 'American Invitational Mathematics Examination',
    description: '15 ข้อ กรอกคำตอบตัวเลข 0–999 — ขั้นกลางระหว่าง AMC 10/12 และ USAMO',
    levels: ['Junior', 'Senior'],
    region: 'USA',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Combinatorics'],
    url: 'https://artofproblemsolving.com/wiki/index.php/AIME_Problems_and_Solutions',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/AIME_Problems_and_Solutions',
    difficulty: 3,
    hasPastPapers: true,
  },
  {
    id: 'mathcounts',
    name: 'MATHCOUNTS',
    fullName: 'MATHCOUNTS Competition Program',
    description: 'Sprint + Target + Team rounds — สำหรับ ม.ต้น (Grade 6–8) เน้นความเร็วและแม่นยำ',
    levels: ['Primary', 'Junior'],
    region: 'USA',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Logic'],
    url: 'https://www.mathcounts.org/resources',
    solutionsUrl: 'https://artofproblemsolving.com/wiki/index.php/MATHCOUNTS',
    difficulty: 2,
    hasPastPapers: true,
  },
  {
    id: 'hmmt',
    name: 'HMMT',
    fullName: 'Harvard-MIT Mathematics Tournament',
    description: 'Individual + Team rounds — ข้อสอบสร้างสรรค์ระดับสูง จาก Harvard & MIT',
    levels: ['Senior', 'Olympiad'],
    region: 'USA',
    topics: ['Algebra', 'Geometry', 'Combinatorics', 'Number Theory'],
    url: 'https://www.hmmt.org/archive/',
    solutionsUrl: 'https://artofproblemsolving.com/community/c594864',
    difficulty: 4,
    hasPastPapers: true,
  },

  // ─── AUSTRALIA ───────────────────────────────────────────────────────────────
  {
    id: 'amc-aus',
    name: 'AMC (Australia)',
    fullName: 'Australian Mathematics Competition',
    description: 'ข้อสอบปรนัยสำหรับทุกระดับ — จัดโดย Australian Maths Trust มีประวัติยาวนาน',
    levels: ['Primary', 'Junior', 'Senior'],
    region: 'Australia',
    topics: ['Algebra', 'Geometry', 'Number Theory', 'Logic'],
    url: 'https://amt.edu.au/department/past-papers',
    difficulty: 2,
    hasPastPapers: true,
  },
  {
    id: 'aimo',
    name: 'AIMO',
    fullName: 'Australian Intermediate Mathematics Olympiad',
    description: '10 ข้อ เขียนแสดงวิธีทำ — สำหรับ Grade 9–10 ขั้นกลางระหว่าง AMC และ USAMO',
    levels: ['Junior', 'Senior'],
    region: 'Australia',
    topics: ['Algebra', 'Number Theory', 'Geometry', 'Combinatorics'],
    url: 'https://amt.edu.au/department/past-papers',
    solutionsUrl: 'https://artofproblemsolving.com/community',
    difficulty: 3,
    hasPastPapers: true,
  },

  // ─── ONLINE RESOURCES ────────────────────────────────────────────────────────
  {
    id: 'aops-wiki',
    name: 'AoPS Wiki',
    fullName: 'Art of Problem Solving — Problem Archive',
    description: 'คลังข้อสอบแข่งขันทุกรายการพร้อมเฉลยจาก community — แหล่งใหญ่ที่สุดในโลก',
    levels: ['All Levels'],
    region: 'Online',
    topics: ['All Topics'],
    url: 'https://artofproblemsolving.com/wiki/index.php/AMC_Problems_and_Solutions',
    difficulty: 3,
    hasPastPapers: true,
  },
  {
    id: 'aops-community',
    name: 'AoPS Forum',
    fullName: 'Art of Problem Solving — Contests & Olympiads Forum',
    description: 'ฟอรัมคณิตศาสตร์ใหญ่ที่สุดในโลก — ถามเฉลย แชร์ข้อสอบ ทุกรายการแข่งขัน',
    levels: ['All Levels'],
    region: 'Online',
    topics: ['All Topics'],
    url: 'https://artofproblemsolving.com/community/c13_contests',
    difficulty: 3,
    hasPastPapers: true,
  },
  {
    id: 'nrich',
    name: 'NRICH',
    fullName: 'NRICH Mathematics (Cambridge)',
    description: 'โจทย์ไม่มาตรฐานจาก University of Cambridge — เน้น Mathematical Thinking ไม่ใช่ท่อง',
    levels: ['Primary', 'Junior', 'Senior'],
    region: 'Online',
    topics: ['Logic', 'Algebra', 'Geometry', 'Combinatorics'],
    url: 'https://nrich.maths.org/secondary',
    difficulty: 2,
    hasPastPapers: true,
  },
]

// Unique regions + levels for filter UI
export const ALL_REGIONS = [
  'Thailand', 'School Open', 'Southeast Asia', 'Asia-Pacific',
  'International', 'USA', 'Europe', 'Australia', 'Online',
] as const

export const ALL_LEVELS = [
  'Primary', 'Junior', 'Senior', 'Olympiad',
] as const
